In [1]:
#rellenar tensor con valores aleatorios
import tensorflow as tf
valores_aleatorios = tf.random_normal([10], dtype=tf.float64)
with tf.Session() as sess:
    print(sess.run(valores_aleatorios))

[ 1.63105215 -0.51085574 -1.19484464 -0.59036092 -0.63997274 -0.52272334
  0.43475471  0.97383497 -0.66986159  0.13907102]


In [5]:
# como usar reshape para cambiar la forma de un tensor
import tensorflow as tf
vector = tf.constant([1., 2., 3., 4.])
matriz = tf.reshape(vector, [2,2])
with tf.Session() as sess:
    print(sess.run(matriz))

[[ 1.  2.]
 [ 3.  4.]]


In [8]:
# como extraer subtensores de un tensor
#elimina la primera dimension y el primer elemento de las otras dimensiones
# y lo transoforma en una matriz dos por dos
import tensorflow as tf
matriz2 = tf.constant([[1., 2., 3.],[4.,5.,6.],[7.,8.,9.]])
slice_matriz = tf.slice(matriz2, [1,1],[2,2])
with tf.Session() as sess:
    print(sess.run(slice_matriz))

[[ 5.  6.]
 [ 8.  9.]]


In [10]:
#combina una lista de tnesores en un tensor de mayor rango
import tensorflow as tf
t1 = tf.constant([1., 2.])
t2 = tf.constant([3., 4.])
t3 = tf.constant([5., 6.])
t4 = tf.stack([t1, t2, t3])
with tf.Session() as sess:
    print(sess.run(t4))

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [11]:
#divide un tensor en una lista de tensores de menor rango
import tensorflow as tf
t1 = tf.constant([1., 2.])
t2 = tf.constant([3., 4.])
t3 = tf.constant([5., 6.])
t4 = tf.stack([t1, t2, t3])
t5 = tf.unstack(t4)

with tf.Session() as sess:
    print(sess.run(t5))

[array([ 1.,  2.], dtype=float32), array([ 3.,  4.], dtype=float32), array([ 5.,  6.], dtype=float32)]


In [12]:
# tambien existe una gran cantidad de operaciones matematicass

In [14]:
#para esto tambien podemos usar los ooperadores normales de pyton +, -, /, *
import tensorflow as tf
a = tf.constant([3., 3., 3.])
b = tf.constant([2., 2., 2.])
sum = tf.add(a,b)
res = tf.subtract(a,b)
prod = tf.multiply(a,b)
div = tf.divide(a,b)
with tf.Session() as sess:
    print(sess.run(sum))
    print(sess.run(res))
    print(sess.run(prod))
    print(sess.run(div))

[ 5.  5.  5.]
[ 1.  1.  1.]
[ 6.  6.  6.]
[ 1.5  1.5  1.5]
