In [2]:
#ejemplo 1
import tensorflow as tf
t1 = tf.constant([1.5,2.5,3.5])
with tf.Session() as sess:
    print(sess.run(t1))

[ 1.5  2.5  3.5]


In [3]:
#ejemplo 2 
import tensorflow as tf
t2 = tf.constant([['c','c'],['c','c']])
with tf.Session() as sess:
    print(sess.run(t2))

[[b'c' b'c']
 [b'c' b'c']]


In [4]:
#ejemplo 3 
import tensorflow as tf
t3 = tf.constant([4,2], tf.int16,[3])
with tf.Session() as sess:
    print(sess.run(t3))

[4 2 2]


In [5]:
#ejemplo 4 para ver que da un error al no coincidir la forma de los valores con el shape que le pasamos
import tensorflow as tf
t3 = tf.constant([4,2], tf.int16,[3], 'Const', True)
with tf.Session() as sess:
    print(sess.run(t3))

TypeError: Expected Tensor's shape: (3,), got (2,).

In [6]:
#ejemplo 5
import tensorflow as tf
zero_tensor = tf.zeros([3])
with tf.Session() as sess:
    print(sess.run(zero_tensor))

[ 0.  0.  0.]


In [1]:
#ejemplo 6
import tensorflow as tf
one_tensor = tf.ones([3, 4])
with tf.Session() as sess:
    print(sess.run(one_tensor))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [3]:
#ejemplo 7
import tensorflow as tf
nine_tensor = tf.fill([3, 4],9)
with tf.Session() as sess:
    print(sess.run(nine_tensor))

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [11]:
#ejemplo 8
import tensorflow as tf
lin_tensor = tf.linspace(5.0, 9.0 , 5)
with tf.Session() as sess:
    print(sess.run(lin_tensor))

[ 5.  6.  7.  8.  9.]


In [12]:
#ejemplo 9
import tensorflow as tf
range_tensor = tf.range(1.0, 10.0 , 2)
with tf.Session() as sess:
    print(sess.run(range_tensor))

[ 1.  3.  5.  7.  9.]
